### ISSUE TITLE
ResourceList Component

### ISSUE THREAD

**Issue by MurmeltierS** [ownego/polaris-vue#131]
Are there any plans to migrate the [ResourceList Component](https://polaris.shopify.com/components/lists-and-tables/resource-list#navigation)? 
Are you open to contributions?

**Comment by juzser** [comment]
Hey there,

We almost finished the ResourceList component, we're writing the documentation. It will be available in the next version.
Demo screenshot: 

<img width="979" alt="Screen Shot 2022-06-14 at 11 01 21" src="https://user-images.githubusercontent.com/5735071/173490685-1f21a2fb-8679-46e3-9b75-c45b973165b9.png">

And we're open to contribute, you're welcome!

**Comment by MurmeltierS** [comment]
@juzser Thanks for the info and keep up the good work!

**Comment by juzser** [comment]
Released at v0.8.2
