### ISSUE TITLE
Sub-Components are missing in the volar.d.ts

### ISSUE THREAD

**Issue by MurmeltierS** [ownego/polaris-vue#133]
Subcomponents like StackItem, ExceptionListItem, ... are missing in the volar.d.ts

**Comment by juzser** [comment]
Double checking...

**Comment by juzser** [comment]
Ok, I figured it out, it's a bit difficult when I have to get the component deeper inside each directory.
Currently `volar.d.ts` file only get component list from `components/index.ts`.

@HQCuong can you help me to update this?
