### ISSUE TITLE
Trying to dev: Missing "Demo.vue"

### ISSUE THREAD

**Issue by tarwin** [ownego/polaris-vue#143]
I've forked the project and am trying to run `yarn dev` but getting the following error:

```
7:30:04 PM [vite] Internal server error: Failed to resolve import "./Demo.vue" from "src/main.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/tarwin/all/development/repos/polaris-vue/src/main.ts
  1  |  import { createApp } from "vue";
  2  |  import Demo from "./Demo.vue";
     |                    ^
  3  |  import PolarisVue from "./polaris-vue";
  4  |  createApp(Demo).use(PolarisVue).mount("#app");
```

There doesn't seem to be a `Demo.vue` anywhere in the repo. Am I missing something?

**Comment by juzser** [comment]
Hi there,

`Demo.vue` is just the file to test components when you dev the lib. 

We added that file to gitignore. 
You can create an empty one, it will work.
