### ISSUE TITLE
ResourceList `:selectable="false"` doesn't disable checkbox

### ISSUE THREAD

**Issue by tarwin** [ownego/polaris-vue#145]
The when setting `selectable` to "false" on `ResourceList` it still shows checkboxes next to each `ResourceItem`.

**Comment by juzser** [comment]
Can you paste your ResourceList conponent here? 
Are you missing colon? It should be `:selectable=“false”`

**Comment by tarwin** [comment]
https://ownego.github.io/polaris-vue/?path=/story/components-lists-and-tables-resource-list--resource-list&args=selectable:false

On the demo it is the same. The checkbox in the heading disappears but the checkboxes next to each item (row) stays there.

**Comment by juzser** [comment]
Fixed on v0.9.1.

**Comment by tarwin** [comment]
Nice work. Totally fixed.

**Comment by juzser** [comment]
@tarwin The DataTable & IndexTable has been updated in v1.0.x
