### ISSUE TITLE
`RangeSlider` error: Failed setting prop "prefix" on <div>

### ISSUE THREAD

**Issue by tarwin** [ownego/polaris-vue#157]
I'm seeing a strange error when using the `RangeSlider`. I set up a minimal test in the repo itself and it still happens. I was not able to debug so bringing it up here.

# Error
![image](https://user-images.githubusercontent.com/646149/179287089-9933c128-64bd-491f-a37e-5f92c364b137.png)

# Test Template
```html
<template>
  <RangeSlider
    label="Test"
    v-model="val"
  />
</template>

<script lang="ts" setup>
  import { ref } from 'vue'
  import { RangeSlider } from '../components/RangeSlider';
  
  const val = ref(0)
</script>

**Comment by juzser** [comment]
#158
