### ISSUE TITLE
Failed to locate Teleport target with selector "#PolarisPortalsContainer"

### ISSUE THREAD

**Issue by a-bormark** [ownego/polaris-vue#174]
`@ownego/polaris-vue` assumes a Vue app is the only content on the page. 

But a Vue 3 app (which uses `@ownego/polaris-vue`) can be injected into a webpage (e.g., Chrome Browser extension, js lib). CSS stylings for the parent can contaminate the app, and stylings for the app can contaminate the parent. A `ShadowDOM` prevents this contamination by isolating the app. However, wrapping the app into the `ShadowDOM` rises the following exception when the app uses `@ownego/polaris-vue` components that use Teleport (e.g, modal, split button, popover, etc.)

`[Vue warn]: Failed to locate Teleport target with selector "#PolarisPortalsContainer". 
Note the target element must exist before the component is mounted - 
i.e. the target cannot be rendered by the component itself, 
and ideally should be outside of the entire Vue component tree. 
  at <Anonymous key=0 idPrefix="popover" >`

`[Vue warn]: Invalid Teleport target on mount: null (object) 
  at <Anonymous key=0 idPrefix="popover" >`

`[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. 
Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Anonymous key=0 idPrefix="popover" >`

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (chunk-IC65DETL.js:2084:27)
    at updateComponent (chunk-IC65DETL.js:5551:9)
    at processComponent (chunk-IC65DETL.js:5511:7)
    at patch (chunk-IC65DETL.js:5226:11)
    at patchBlockChildren (chunk-IC65DETL.js:5447:7)
    at processFragment (chunk-IC65DETL.js:5491:9)
    at patch (chunk-IC65DETL.js:5220:9)
    at patchBlockChildren (chunk-IC65DETL.js:5447:7)
    at Object.process (chunk-IC65DETL.js:6244:9)
    at patch (chunk-IC65DETL.js:5228:16)`

### The solution
In a codebase where `#PolarisPortalsContainer` is queried ([Portal.vue](https://github.com/ownego/polaris-vue/blob/b02e96df9524ee0bdca899a3d7e5b14488741b1a/src/components/Portal/Portal.vue) and [PopoverOverlay.vue](https://github.com/ownego/polaris-vue/blob/f1a27ef836b4d27bc23c26ab91dfc5aa6edff869/src/components/Popover/components/PopoverOverlay/PopoverOverlay.vue)) run `.querySelector('#PolarisPortalsContainer')` against the `ShadowRoot` (instead of the `document`) if the app is wrapped in a `ShadowDOM` (as a new option for `app.use(PolarisVue)`)

**Comment by juzser** [comment]
Have you missed to wrap the `AppProvider` component at root?

**Comment by a-bormark** [comment]
Thank you for your reply. Yes, the app has been wrapped with `AppProvider`.

**Comment by juzser** [comment]
It's strange, because the teleport component is supported native by vue3, then we just have to add the container to AppProvider, and then vue does the trick. So even your solution is ok but we cannot update cause it's in the vue core.

We're also using the Popover and teleport components and seems like never face this problem before.

Do you have any example or repo do reproduce the issue? Or create in sandbox editor, then I can take a look and fix.

**Comment by juzser** [comment]
Hey @a-bormark , I think I get your issue. 
Maybe because you're showing the modal in `v-if`, that means the modal at initialization was not existed, so it cannot be mounted to the Portal Container. 
So to avoid this issue, your modal should exist in the DOM at the beginning; And use `open` props to define when it should be shown. 

That means, the modal should always there, just show up or hidden by open ref (not v-if)

**Comment by juzser** [comment]
Close due to inactivity.

**Comment by a-bormark** [comment]
> Hey @a-bormark , I think I get your issue. Maybe because you're showing the modal in `v-if`, that means the modal at initialization was not existed, so it cannot be mounted to the Portal Container. So to avoid this issue, your modal should exist in the DOM at the beginning; And use `open` props to define when it should be shown.
> 
> That means, the modal should always there, just show up or hidden by open ref (not v-if)

I would argue that this is not a viable solution, as the dialogue lives inside multiple inherited components, and those components are controlled by v-if. But anyways, we've solved it by patching the lib with a solution from my very first comment. Many thanks.
