### ISSUE TITLE
Error when using with Nuxt 3 

### ISSUE THREAD

**Issue by naveensky** [ownego/polaris-vue#178]
I am trying to integrate this plugin with Nuxt 3 and I am getting the following error. I have created a basic repo to reproduce the error at https://stackblitz.com/edit/nuxt-starter-bbhctu

```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function                                                                                             09:39:06
  at ./node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:38:256  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:151:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:153:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:97:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:107:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:29:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
```

Any idea how to resolve this error?

**Comment by juzser** [comment]
@naveensky 
Sorry, currently our package does not support Nuxt. 
To integrate with Nuxt, I have to update a bit, to package as SSR module.

I will check and update this in the next versions.

**Comment by naveensky** [comment]
@juzser - Thanks for confirming this. Is this something I can help? We are considering this module to set up a Shopify app and would love if we can somehow contribute to making it Nuxt compatible.

**Comment by juzser** [comment]
Actually, I'm not familiar with Nuxt so I need to research first. 
But as I understand, you can try to read this doc: [Write you own module](https://nuxtjs.org/docs/directory-structure/modules/#write-your-own-module) and [this](https://nuxtjs.org/docs/directory-structure/plugins/#client-or-server-side-only)

I'm really happy if you can contribute by PR, or you can tell me the way to do, then it's more easier for me to integrate. 
Thank you!

**Comment by naveensky** [comment]
@juzser - The links you shared are for Nuxt V2. I guess since you are Vue3 compatible, you should target Nuxt 3. 

I tried setting up the plugin via https://nuxt.com/docs/guide/directory-structure/plugins#vue-plugins but was getting the same error

I will search within Nuxt community to understand if there is a better way to bundle your plugin

**Comment by naveensky** [comment]
@juzser  - It seems you are using an outdated version of vue-router. Look at the comment at https://github.com/nuxt/nuxt/issues/18891#issuecomment-1423175135

Do you think you can upgrade it to the latest one and I can try again integration it with nuxt

**Comment by juzser** [comment]
@naveensky Sure, that's a mistake, the `vue-router` is not necessary in this package, I'm going to get rid of it.

**Comment by naveensky** [comment]
@juzser - that would be great, I have been running a local build and I am able to use it with the latest version of Nuxt. Once you update your build, I can send a PR with instructions on how to use it. 

Do you think we can use the latest version of Vue3 as well?

**Comment by juzser** [comment]
Done, I've built the v1.3.1, you can try again

**Comment by naveensky** [comment]
@juzser - The new build works just fine, with few warnings though.  I will send PR with instructions to work with Nuxt3

**Comment by juzser** [comment]
@naveensky Cool! Thank a lot!

**Comment by naveensky** [comment]
@juzser - I added the instructions on usage with Nuxt 3 at https://github.com/ownego/polaris-vue/pull/179

Please feel free to update the usage to match your style guidelines

**Comment by juzser** [comment]
Thank you @naveensky 👍🏽 
The PR has been merged. I will update the doc page in the next version, currently README is enough. 
I'm going to close this issue.
