### ISSUE TITLE
Frame using script setup

### ISSUE THREAD

**Issue by mariusa** [ownego/polaris-vue#182]
Hi, thanks for this library!

I'm trying to render some content in a `Frame`.
I see some components use `<script setup>`, but not this one: 
https://ownego.github.io/polaris-vue/?path=/docs/components-frame--frame

Would it be possible to update it to use  `<script setup>` too?

Thanks!

PS: Is there a hello world full app example?

**Comment by juzser** [comment]
@mariusa Of course you are, the `script setup` does not related to the component itself, you can use composition API or options API, it's up to you. 

I don't have an full app example but I'm using the library for all of my apps, and I see it works well. 
I will update or fix bug if there is something wrong.
