### ISSUE TITLE
Card secondaryFooterActions open in a weird place

### ISSUE THREAD

**Issue by mydnic** [ownego/polaris-vue#188]
This is my code 

```html
<Card
    :title="mail.subject"
    :primaryFooterAction="{ content: 'Send Reply' }"
    :secondaryFooterActions="[
        { content: 'Move To Pending' },
        { content: 'Mark as refunded' },
        { content: 'Close', destructive: true },
    ]"
>
    <CardSection>
        <p>
            {{ mail.body }}
        </p>
    </CardSection>

    <CardSection>
        <TextField
            v-model="formData.reply"
            autoComplete="off"
            label="Reply Message.."
            :multiline="4"
        />
    </CardSection>
</Card>
```

This is the result when I click on the "More" dropdown :

![Screenshot 2023-04-24 at 18 40 33](https://user-images.githubusercontent.com/2733767/234061494-21c3ccb5-0c18-4697-a1d4-9f6704699d32.png)

It's like the menu has an absolute position but with no relative parent and thus it goes on the top left of the screen.

When I click a second time, the menu disappear (ok) and then when I click a 3rd time, nothing happens. I have to refresh the page to make it show again.

Thanks a lot :) 

I'm using `"@ownego/polaris-vue": "^1.3.6",` btw

**Comment by juzser** [comment]
Fixed on `v1.3.7`
