### ISSUE TITLE
v1.3.7 cannot be installed

### ISSUE THREAD

**Issue by LonnyX** [ownego/polaris-vue#192]
Hello

I tried to migrate from v1.3.5 to v1.3.7 and I receive this message:

```
The engine "node" is incompatible with this module. Expected version "^14.17.0 || ^16.13.0". Got "20.0.0"
error Found incompatible module.
```

I also see that the  loading state is not working on the `ContextualSaveBar` button but that can be part of another issue if you want

PS: after downgrading Node to v16 the update was OK. I don't know why it was working on V1.3.5

**Comment by ohstable** [comment]
Same installation issue for me as well. downgraded Node to 16.13.0 no luck. 

`deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility`

It gets stuck display the above errors for few minutes and then fails with bunch of deprecated errors.
