### ISSUE TITLE
OptionList: ReferenceError: value is not defined

### ISSUE THREAD

**Issue by pohnean** [ownego/polaris-vue#194]
The OptionList component is giving a `ReferenceError: value is not defined` error when `allow-multiple` is enabled.

<img width="1144" alt="image" src="https://github.com/ownego/polaris-vue/assets/846343/e33a9521-0eee-4215-a61e-48d1bfdb2c2b">

**Comment by blacklen** [comment]
Hi Pohnean, this is just a problem with the docs. It won't happen when you use it.

**Comment by pohnean** [comment]
I’m actually encountering the issue when using the library, not just in the docs site.I’m on Vue 3.3.Best Regards,Poh NeanOn 6 Jun 2023, at 3:49 PM, Huong ***@***.***> wrote:﻿
Hi Pohnean, this is just a problem with the docs. It won't happen when you use it.

**Comment by blacklen** [comment]
Sorry Pohnean, my bad.

I've fixed it in `v1.3.9`, you can try and let me know if the issue still occurs.

Thanks,

**Comment by pohnean** [comment]
Awesome! Thanks for the quick response! I wanted to create a PR but wasn’t able to run storybook locally so I ended up writing a custom OptionList yesterday.
