### ISSUE TITLE
Process of creating components

### ISSUE THREAD

**Issue by naveensky** [ownego/polaris-vue#197]
Hi Team, 

This library has been really helpful, and I would like to start using it more with our projects. 

I am concerned with the future of this library. I would like to understand if you are migrating React code to Vue or creating components using the default Shopify Polaris CSS

I would also would love to understand how frequently do you plan to update this library with newer components or are open to PRs from the community for the same, 

Thanks,

**Comment by juzser** [comment]
Hey, 

Currently we're still using this lib for all of our projects, then we're still updating and fixing the common issues for it. 

The core of this library is we migrate from Shopify React code to Vue, not only using Polaris CSS. 

About the future plan, actually we have a plan to upgrade the library for Polaris v12 (Shopify beta it soon) but it will change a lot of things, and the current projects have to be changed and migrate from beginning, then we're still researching, and by the way, we do not have enough resources to migrate it quickly. 

So, PRs from community are welcome, really appreciate!

**Comment by naveensky** [comment]
@juzser - Thanks for clarifying. I will be happy to help as I love this project and if you have open issues on this GH repo or somewhere else, please let me know. 

I would love to improve the quality of this project (though its really top-notch) but there are certain warnings when using with nuxt and somehow I am unable to use few components correctly. 

Is the process of migrating code from react -> vue is automated or needs manual effort?

**Comment by juzser** [comment]
We have to convert manually, and I see it will take a lot of time. 
About the roadmap or list of issues, currently we compare the changes of each version and each one will take care a few of specific components. 

So simply one issue is one component, I will take a look and create some first issue if you need. 

You can check a component and see mostly the core logic comes from Shopify, we just do one job: avoid react from source and try to make everything easy for Vue users (create slots, props,...)

**Comment by betelgeus13** [comment]
Do you guys have WIP PR or a fork for polaris 12?

We'd like to use this lib once it's on v12. 

If you have a list of missing components we can try to jump in and help a bit

**Comment by juzser** [comment]
@betelgeus13 @naveensky v2 is out now, guys! 
You can check it out, and can see the [Contributing](https://ownego.github.io/polaris-vue/contributing) article here.
