### ISSUE TITLE
Nuxt3 Boilerplate

### ISSUE THREAD

**Issue by SteveChurch** [ownego/polaris-vue#198]
This is great, really nice to see, I came across it today during my lunch when just looking around to see if anyone has ported these. My following question is: 

Do you have a NuxtJS/Vue3 boilerplate which you use this with for Shopify development? 

I was thinking of cobbling one together but though I would ask first. 

Thanks

**Comment by juzser** [comment]
Currently we do not have any Nuxt3 boilerplate to send to you.
But as I know @naveensky is also using the package with Nuxt3 (as he contributes the guide to integrate with Nuxt3 in README) 
Hopefully he can help you. 

But I think it's easy to use then you can find any Nuxt3 boilerplate and then think about setup `polaris-vue` later.

**Comment by naveensky** [comment]
@SteveChurch - I don't have a boiler plate ready but it's a simple two-step process. I documented it at https://github.com/ownego/polaris-vue#nuxt-3

Let me know if you have any queries, happy to help

@juzser - just curious, what platform do you use to build your app?

**Comment by juzser** [comment]
@naveensky We build from scratch, using TS & Vue only (SPA), Laravel for BE - API. 
Actually I'm not a fan of Nuxt.

**Comment by naveensky** [comment]
@juzser - just curious, but do you see your app getting more traction after "built for shopify" badge?

**Comment by juzser** [comment]
@naveensky Surely do. The app's ranking is greatly boosted.

**Comment by juzser** [comment]
@SteveChurch Close during non activity. Feel free to re-open.
