### ISSUE TITLE
Individual Import Issue -

### ISSUE THREAD

**Issue by shriDeveloper** [ownego/polaris-vue#200]
![image](https://github.com/ownego/polaris-vue/assets/33655616/52fa0e1e-7c83-4948-afcc-f675bd3bdf44)

I am trying to reduce the bundle size for my app , also , i would like to know , how can we do it ?

Because , at the moment , if i try to import only the components i want , it fails with error - content is null.

**Comment by juzser** [comment]
Actually, Shopify develops the components with chain, I mean mostly components will be linked to others. 
So we've tested and see, even if you're using individual import, you still have some other components imported, then the bundle size just can be reduced not too much. 

By the way, can you provide the screenshots of error?

**Comment by juzser** [comment]
Close due to inactivity.
