### ISSUE TITLE
it renders <a download=false>

### ISSUE THREAD

**Issue by sarim** [ownego/polaris-vue#201]
When "download" attribute is not needed, it should not render a download attribute. Otherwise browser is downloading a "false.htm" instead of navigating to the url.

Interestingly I doesn't happen in top frame, but inside iframe browser download it instead of navigating.

**Comment by juzser** [comment]
What're you talking about? You should make a question with full context & details, then we can check. 

Which component are you using? 
Do you have example? You should provide your use case.

**Comment by sarim** [comment]
@juzser I encountered it in banner component. But I suspect root cause is from Button? 
https://github.com/ownego/polaris-vue/blob/master/src/components/Button/Button.vue#L77

For demonstration go here: https://ownego.github.io/polaris-vue/?path=/docs/components-banner--banner
![image](https://github.com/ownego/polaris-vue/assets/1235888/2e548a98-6067-4cf2-a94b-2ebfa452eb97)

**Comment by juzser** [comment]
Fixed on v1.3.10
