### ISSUE TITLE
Optimize Documentation for User-Friendly Experience

### ISSUE THREAD

**Issue by adityash97** [ownego/polaris-vue#204]
I've been exploring the ownego/polaris-vue library and I've noticed that the current documentation can be improved to make it more developer-friendly, especially for newcomers.

1. **Enhanced "Get Started" Page**: The "Get Started" page should provide more detailed, step-by-step instructions on how to set up and start using ownego/polaris-vue. This can include:

-   Clear installation instructions.
-   A simple example to demonstrate the core concepts.

2.  **Import Statements in Code Sections**: It would be extremely helpful to include import statements in the code sections of each component in the documentation. This makes it easier for developers to understand how to include and use the components in their own code.

These improvements would go a long way in making it more convenient for developers, especially those who are new to the library, to get started and use ownego/polaris-vue effectively.

**Comment by juzser** [comment]
Thanks for your recommendations, we will update the doc soon. 
I guess the problem is just it's missing real case study or a demonstration with mostly components.

**Comment by juzser** [comment]
@adityash97 You can check the doc of v2. It's mostly similar with Shopify.
