### ISSUE TITLE
Toast is not working

### ISSUE THREAD

**Issue by shriDeveloper** [ownego/polaris-vue#205]
Hi Guys , Is Toast working for you ? I have a toast inside a frame ,, but it's not rendering .
Gives error - hideToast is not a function.
Any help ?

**Comment by juzser** [comment]
@shriDeveloper I see the Toast is working well. Can you give me some screenshots or some lines of code? 

By the way, if you're developing embedded app, you should use native Toast via AppBridge from Shopify.

**Comment by juzser** [comment]
Close due to inactivity
