### ISSUE TITLE
IndexTable gives error in console

### ISSUE THREAD

**Issue by shriDeveloper** [ownego/polaris-vue#207]
Whenever i use IndexTable , i get this error in the console :-

Uncaught TypeError: T.value.getBoundingClientRect is not a function

**Comment by shri-simcorner** [comment]
Complete log :-
Uncaught TypeError: T.value.getBoundingClientRect is not a function
    at X (polaris-vue.es.js:16468:63)
    at se (polaris-vue.es.js:16558:7)

**Comment by juzser** [comment]
That error log happens when you change the viewport size (change screensize, like: open the Developer tool and scale up/down the console to test responsive, vice versa...). 
I know that error, but it does not effect the whole app. 

We will try to fix this in the next versions.

**Comment by shriDeveloper** [comment]
May i know , when this will get fixed please ?

**Comment by juzser** [comment]
Fixed on [v1.3.11](https://github.com/ownego/polaris-vue/releases/tag/v1.3.11)
