### ISSUE TITLE
Missing AnnotatedSection component since 1.3.0

### ISSUE THREAD

**Issue by mcorraodab** [ownego/polaris-vue#208]
Hello there,

We've just started using this package and we've noted that the AnnotatedSection.vue file is missing from the NPM package on version 1.3.10.
And it seems the component is missing since v1.3.0 (but present on v1.2.0)

You can confirm this navigating the code published here: [https://www.npmjs.com/package/@ownego/polaris-vue](https://www.npmjs.com/package/@ownego/polaris-vue) 

Would you guys be able to add it back to the package?

Thank you in advance, keep up the good work!

**Comment by juzser** [comment]
Hey, the AnnotatedSection component is still here: https://github.com/ownego/polaris-vue/blob/master/src/components/Layout/components/AnnotatedSection/AnnotatedSection.vue
Can you capture a screenshot the error you're facing?

**Comment by mcorraodab** [comment]
Hi again,

Just for context, the main problem that we're having is that we cannot use the AnnotatedSection component. We can use successfully other components such as the Layout component, but <AnnotatedSection> didn't work.

I asked 3 different people to pull the code using the "npm install" command and they all didn't have the AnnotatedSection.vue file inside.

That's when we checked and we found that the vue file was missing inside vendor folder. Thought it might be related.

Thanks again guys!

**Comment by juzser** [comment]
Thank @mcorraodab we're looking on it.

**Comment by juzser** [comment]
Fixed on [v1.3.11](https://github.com/ownego/polaris-vue/releases/tag/v1.3.11)

**Comment by mcorraodab** [comment]
Great guys, I can confirm it's working. Thanks for the awesome work, keep it up!
