### ISSUE TITLE
Possible Improvement for Listbox Styling

### ISSUE THREAD

**Issue by vildanbina** [ownego/polaris-vue#218]
I've been working with the Combobox component and encountered some styling discrepancies compared to the documentation. I've developed a code snippet that seems to address these styling issues, but I'm unsure if this is the best approach.

Here is the improved code snippet:

```html
<Listbox accessibilityLabel="Basic Listbox example">
    <ListboxOption value="1">
        <ListboxTextOption :selected="true">
            Option 1
        </ListboxTextOption>
    </ListboxOption>
    <ListboxOption value="2">
        <ListboxTextOption>
            Option 2
        </ListboxTextOption>
    </ListboxOption>
    <ListboxOption value="3">
        <ListboxTextOption>
            Option 3
        </ListboxTextOption>
    </ListboxOption>
</Listbox>
```

I'm reaching out to inquire if this is an appropriate solution or if there is a different recommended way to achieve the correct styling as per the documentation. Additionally, if this approach is valid, it might be beneficial to update the documentation to include this improved snippet for the benefit of other developers.

Your guidance and insights on this matter would be greatly appreciated.

**Comment by juzser** [comment]
@vildanbina Can you attach a screenshot of the UI you get, together with the element inspection of this? 
I guess there is no `<ListboxTextOption>` component.

**Comment by vildanbina** [comment]
@juzser regarding on code without `ListboxTextOption`, 
```html
<Listbox accessibilityLabel="Basic Listbox example">
    <ListboxOption value="1">Option 1</ListboxOption>
    <ListboxOption value="2">Option 2</ListboxOption>
    <ListboxOption value="3">Option 3</ListboxOption>
</Listbox>
```

and the result: 

![image](https://github.com/ownego/polaris-vue/assets/51203303/d4e8277c-8f62-4fdc-8ef1-396c33047a63)

**Comment by juzser** [comment]
Do you have the element structure as example in doc? (screenshot below)
<img width="1310" alt="Screenshot 2023-12-14 at 09 03 41" src="https://github.com/ownego/polaris-vue/assets/5735071/726107bf-8b2c-4428-bd89-f6a94870360a">

Have you wrapped the whole site in `<AppProvider>` component?

**Comment by vildanbina** [comment]
yes, they are all the same. The issue seems to be that `ListboxTextOption` is not included by default in the `ListboxOption` component. Once `ListboxTextOption` is added, everything appears to function correctly

**Comment by vildanbina** [comment]
@juzser, do you have any possible solutions for this? 

btw when will the new version of `polaris-vue` be released? I've noticed differences in components compared to Shopify, and there are some things that don't work here

**Comment by juzser** [comment]
@vildanbina I cannot reproduce your issue, so I cannot help. Could you create an example on CodeSandBox or some where that I can look into it? 
Or at least capture an inspected element screenshot.

About the next version, we're working on it, and have a plan to release on QI, 2024. 
The first screenshots: 

<img width="1428" alt="Screenshot 2023-12-19 at 09 24 36" src="https://github.com/ownego/polaris-vue/assets/5735071/e835aae2-5f4e-4c9f-a106-cf7d73c55ab1">
<img width="929" alt="Screenshot 2023-12-19 at 09 24 07" src="https://github.com/ownego/polaris-vue/assets/5735071/9d0f9fb2-c397-4683-bee9-26c98ff2b2c5">

But you should check the prerequisites below to see if your project is compatible with the new version: 

<img width="1009" alt="Screenshot 2023-12-19 at 09 24 30" src="https://github.com/ownego/polaris-vue/assets/5735071/8cee41bd-f40e-41d7-b9ad-3ffb3b74cc4a">
