### ISSUE TITLE
Date Picker on Version 2 does not show Month, Days

### ISSUE THREAD

**Issue by canhnm** [ownego/polaris-vue#360]
Hello,

We are testing Polaris Vue 2.0.1 and noticed there are issues on Date Picker component (https://ownego.github.io/polaris-vue/components/DatePicker) as it does not show Month and Day as attachment image
![image](https://github.com/ownego/polaris-vue/assets/705656/3a11a427-95c0-4ef6-9ca5-c2ac4412c66c)

**Comment by juzser** [comment]
Have you added the `i18n` prop into `AppProvider`? 
You can follow this example: [AppProvider with i18n](https://ownego.github.io/polaris-vue/components/AppProvider?example=app-provider-with-i18n)
The locale should be `en` if you're using English.

**Comment by canhnm** [comment]
> Have you added the `i18n` prop into `AppProvider`? You can follow this example: [AppProvider with i18n](https://ownego.github.io/polaris-vue/components/AppProvider?example=app-provider-with-i18n) The locale should be `en` if you're using English.
> 
> Edit: I've updated the doc for AppProvider locale: [here](https://ownego.github.io/polaris-vue/documentation#appprovider) The list supported locales: [here](https://ownego.github.io/polaris-vue/utilities#locales)

Thank you for your reply, I have added i18n prop into AppProvider and it works well!
