### ISSUE TITLE
Combobox Text field automatically focused on page load

### ISSUE THREAD

**Issue by canhnm** [ownego/polaris-vue#363]
Hello,

I am using ComboboxTextField and there is an issue with the auto focus functions.
On 1st page load or refreshing the input field will be automatically focused how to avoid that?
![image](https://github.com/ownego/polaris-vue/assets/705656/4888e30b-c2b4-458a-975f-9a5b8ac5f5d0)

I tried with autoComplete="off" / focused=false / autoFocus=false but still not working as expected!

**Comment by juzser** [comment]
Can you provide some lines of your scripts? 
I guess you can try `:autoFocus="false"` for `AutocompleTextField`

**Comment by canhnm** [comment]
> Can you provide some lines of your scripts? I guess you can try `:autoFocus="false"` for `AutocompleTextField`

Hello, I tried with autofocus="false" with AutocompleteTextField but it does not work as expected! 
On first page load or refresh the input field still being autofocused!
