### ISSUE TITLE
[Index filters] Tooltip should match when using hide-filters attribute

### ISSUE THREAD

**Issue by kylewallace8438** [ownego/polaris-vue#367]
Issue: When I want to disable filter/search option, the tooltip below still shows the text for search and filters
Expectation:
- When using hide-filters attribute, tooltip should show **Search**
- When using hide-query-field attribute, tooltip shoulld show **Filter**
![image](https://github.com/ownego/polaris-vue/assets/28037769/a9ca671e-1986-4d43-9ddb-21008440eeec)

**Comment by juzser** [comment]
Have you solved this?

**Comment by kylewallace8438** [comment]
Ah yes, I found filteringAccessibilityTooltip prop to customize the tooltip
