### ISSUE TITLE
Documentation for version 1.3.*

### ISSUE THREAD

**Issue by kylewallace8438** [ownego/polaris-vue#368]
I'm currently working on a project using @ownego/polaris-vue (1.3.9)
Since the documentation page was updated, I wonder if your team has the old documentation somewhere else
It'd be nice if I can access to the old docs
Thank you!

**Comment by juzser** [comment]
Yeah, I thought about it before, because our team is also using v1.x (upgrading to 2.x) 
I will find a way to live it on another url.

**Comment by juzser** [comment]
Hey @kylewallace8438 
I've published the doc for old version here: https://ownego.github.io/polaris-vue/v1/
You can try.

**Comment by kylewallace8438** [comment]
Thank you so much!
