### ISSUE TITLE
Incorrect Import Path in Documentation

### ISSUE THREAD

**Issue by KarDev** [ownego/polaris-vue#369]
The example code in the documentation at [https://ownego.github.io/polaris-vue/documentation#appprovider](https://ownego.github.io/polaris-vue/documentation#appprovider) incorrectly imports the locales file directly from the @ownego/polaris-vue/locales directory. This path does not reflect the actual location of the locales file in the distributed package.

**Comment by KarDev** [comment]
I have submitted a pull request to correct the import path in the example code. The PR updates the path to @ownego/polaris-vue/dist/locales/en.json, aligning it with the actual location in the distributed package. You can find the PR here: [#370](https://github.com/ownego/polaris-vue/pull/370) 

This change should resolve the issue by ensuring the documentation accurately reflects the correct import statement for the locales file. Please feel free to review and merge at your convenience.

**Comment by HQCuong** [comment]
Hi @KarDev, thanks for reaching us. According to your report, we just have a quick check and realize there's still another missing import path. So i will create a new PR and you can close your PR.
You can check to my PR here https://github.com/ownego/polaris-vue/pull/371
Thank you.

**Comment by KarDev** [comment]
Thank you for the prompt review and for identifying the additional issue with the import path. I'm glad to contribute to the improvement of the documentation. I will close my PR [#370] as suggested and take a look at the changes proposed in your PR [#371].
