### ISSUE TITLE
Request for Changelog or Release Notes for Recent Versions

### ISSUE THREAD

**Issue by KarDev** [ownego/polaris-vue#372]
I am a user of @ownego/polaris-vue and am currently on an older version (1.3.8). I'm planning to upgrade to the latest version and would like to review the changes, fixes, and new features introduced since my current version.

I could not find a detailed changelog or release notes in the repository or the documentation. Could you please provide this information or guide me to where I can find it? Having access to the changelog would greatly assist in understanding the impact of the upgrade and implementing any necessary changes in my project.

Thank you for your support and for the great work on @ownego/polaris-vue.

**Comment by juzser** [comment]
Hey @KarDev , 
Actually the v2.x of polaris-vue is totally different from v1.x. 
v2.x is based on Shopify Polaris v12.x. 

To migrate from v1.x to v2.x, you should check to see if your components deprecated or not (some: Subheadings, TextStyle,...) and migrate components from [Deprecated](https://ownego.github.io/polaris-vue/components/deprecated) category.

Mostly properties of un-deprecated components we do not change too much, but some, yes. 

The update is too big so we cannot provide a full changelog. 

You can ask any question or create issue here, we will help.

**Comment by juzser** [comment]
I think the major change of your project may be the Vue version.

**Comment by KarDev** [comment]
Hey @juzser ,

Thank you for the quick response and guidance on migrating to v2.x of polaris-vue. I'll check for deprecated components and reach out if I have any questions during the process.

Appreciate your support!
