### ISSUE TITLE
[Vue warn]: Component is missing template or render function

### ISSUE THREAD

**Issue by giapdong** [ownego/polaris-vue#381]
When I used the sample code of [IndexFilters](https://ownego.github.io/polaris-vue/components/IndexFilters) I found a lot of warning 
![image](https://github.com/user-attachments/assets/de606f81-3e0e-4214-a5a9-803603ccc793)
After a long time to debug, I found a problem appearing in `IndexTableBase` component when rendering heading, details function renderHeading always return an array of VNode
![image](https://github.com/user-attachments/assets/d95c2b47-90de-4f5b-bce2-78a4f7b91f8f)
But when render in `Sticky`, this result used as a VNode (First arrow), in `ScrollContainer` do not appear warning because it used v-for
![image](https://github.com/user-attachments/assets/b236ba2e-1a8c-45d0-bb8a-5312d4ed1da2)

I was think make a commit to resolve, but not sure logic behind the sense and side effect. So I wish team will fix it soon

**Comment by juzser** [comment]
Fixed on [v2.1.4](https://github.com/ownego/polaris-vue/releases/tag/v2.1.4)
