### ISSUE TITLE
Media card bug

### ISSUE THREAD

**Issue by AEDevSolutions** [ownego/polaris-vue#385]
Hi!

https://ownego.github.io/polaris-vue/components/MediaCard?example=media-card-video-card#

In React Polaris: 
![2024-08-07-09-23-37](https://github.com/user-attachments/assets/652c80b4-4bc8-4f47-aca8-f4aface2eadb)

In Vue Polaris:
![2024-08-07-09-23-02](https://github.com/user-attachments/assets/fa661ba4-de50-4628-ad3a-ab5a5051ff9e)

Please help!

**Comment by juzser** [comment]
Fixed on v2.1.5
