### ISSUE TITLE
Select Bug

### ISSUE THREAD

**Issue by cbodtorf** [ownego/polaris-vue#386]
I noticed this in docs, as well as locally.

Visually it looks like the Select is working, but the native `select` element's value is being reset, or set to an empty string.

Only on the second time of clicking the option will it get set properly.
![Kapture 2024-08-08 at 15 57 58](https://github.com/user-attachments/assets/d7f387f7-dc1b-4679-8f59-5aa504a619fe)

**Comment by juzser** [comment]
Fixed on v2.1.6
