### ISSUE TITLE
Feature request: Custom portal target

### ISSUE THREAD

**Issue by nickmessing** [ownego/polaris-vue#389]
In the current implementation `#PolarisPortalsContainer` is hardcoded as portal's target. This doesn't work with [defineCustomElement](https://vuejs.org/guide/extras/web-components#definecustomelement) because `#PolarisPortalsContainer` is inside a shadowRoot so it can't be found from the `document`. Adding an `InjectionKey` that can be used to `provide` custom portal target should solve for this usecase.

**Comment by juzser** [comment]
If you're doing correctly with `AppProvider` component, so you can try to inject `portals-manager`, the output will be Portal element.

```js
const portal = inject('portals-manager');
```

**Comment by nickmessing** [comment]
@juzser, that doesn't cover this usecase. `Portal` component uses `Teleport`'s `to` prop and sends a [hardcoded string](https://github.com/ownego/polaris-vue/blob/master/src/components/Portal/Portal.vue#L25) to it. Vue [uses browser's `querySelector`](https://github.com/vuejs/core/blob/main/packages/runtime-core/src/components/Teleport.ts#L386) to find the element.
If we use custom elements - the `#PolarisPortalsContainer` is not accessible from browser's `document` because it's inside a [ShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot). 

If we change:
```pug
teleport(
  v-if="container",
  :to="PORTAL_CONTAINER_ID",
)
```
to
```pug
teleport(
  v-if="container",
  :to="container",
)
```

It works as expected since `AppProvider` already provides the portal container in `portals-manager` and the `Portal` component already injects it.

Should I open a PR?

P.S. We have a giant vue 2 app that we can't migrate to vue 3 yet so as a microftontend-like architecture we're building custom elements using vue 3 and we're using `@ownego/polaris-vue` in vue 3. This is the only issue I have faced so far.

**Comment by nickmessing** [comment]
@juzser [minimal reproduction](https://play.vuejs.org/#eNqdVlFv4zYM/iuCB5wdILW32wYMWVK0Kzqge9gVbdGXpji4tpK4UyRPktMUufz3fZIsW05y23B5iUV+FMmPFKVddFnX6aah0SSaqkJWtSYs58vZPNJqHp3PebWuhdRkR5ZUXzVSUq5vuNI5LyjZk4UUaxLDPu6QcZoVjdJifUYZXQOeagXtnNOt1Zd0kTcMO875fs6nmfMKT1houq5ZrilWhEyH25AM0mkWQKJx5HyerfM6fVWCIwtsS8i8VSCFiXFE8JtHF+KN06XIasFyWakzhG3082ilda0mWVaUHNuUlFUbmXKqM16vsxNWWVkpnVEVymA4j4wnJLVHZFoVgi+q5UFchVjXFaPyU60rwYfx5YyJtz+sTMuGjr28WNHirxPyV7V18d9KqqjcIJtOp3OJgjn19f2fdIvvTrkWZcPa3L+ivKNKsMbE6GC/NbxE2AHORntjaa748kFdbzXlyidlArVsWPw8AkNX/5J6H+6P6U8Bi8bGt2dQ+WlZbchE6XdG0am7Fa2WKz0h8cePP9fbeG8bFw102WhhCGdU22AImQjnHFbtlysaNAp9VmhaQuU/u0gd5MLJAWjqEoHc26WlyACsT3j1cZLvNJj9vaKsbFUHIT14tdcSnL0XyuDgIV92bs1vc4ayWE3F60Y/5sz0bq+Hw4KuBCupBOae5rJYhfocbg2Xxq3JfbEItRd20y4vE1evNsfOhh4ePbMMU7FHE0U5PKJYtlNFUd3UX5stki4Gw+TXQBe6GQ9WHX+d7YmzakcPjqIyk+egsGRGnkwuu43hE/0jMXGqIh67OkBw5wSuiztYznX1N7bucZet5AC4qfg7C2CPdn0M0vky3A0wKzkAgqVGvlRqRcswxEBqDJ5Bns/4OF/sMVVa4sQ+PZ8nT88joB22b6wB7DyJ4x7UHhqHSI4INUAP7XsJ6OQzErjeYIyPSZuO235EZuduDPT+U4uAlf23W0K9IEkrn80IYvLDow2pMzoKChsYnEQDSm4XGC7mz8W5qJim8o4u6RbWnL4RfF9va+dtTOLK5u/hGLW4vXpCj9ylbsMkcYGZBMNAU1u3dJ3rYpUEvke21o7A46QGXoHZHxHdDSPDtg/Js4w6dzwPO8MX3K8RWJ109jc4yr2lt7Wx+3xhOwgW6fMyTN7b+gp4Hhza8TDw19Zr7z9as6HXDx+GAkerq64n8bAwnkwvt+gTbTfg5un7Z/LlCxrOsB68V3A5HT1zcEt1YwvPnIrTKwu5dogxWZ1+Mt26cfVo2g0Dr65vpdhUmOX/Mdg6Z4WkaAEYnt7//z/ezB3RytPMX77BCM3hYta7S3b7kVFCnDaKJn0iVtydGNjkb3mFw0ZNueNve3AxUeQMry5qjASP4aMdXT/8YvrQuYA7q066EASjKRPLxMCcMKyKSl2pknhYT4zYEzVMbDfbyyzpRpCLwlxLgocUz07wbsIyNp9eXtFkaa5UteTJkW0KSq8ENy+IsWE9/QwnZnXS/Nie5Irk/H2U1q6V1HCXTmz5CE4ZksKRXSVBE5qetAzv0cCJaYqRDcI80UajaP8POIQ/Ww==) (missing styles but the teleport target problem is there)

**Comment by juzser** [comment]
@nickmessing Got it, the PR looks good to me. Thank you. 
I see you're building Richpanel, that's good product 👍🏽  Good to hear from you & connect.
