### ISSUE TITLE
Use an icon as prefix for TextField

### ISSUE THREAD

**Issue by alessmar** [ownego/polaris-vue#398]
I know this isn't an issue with your library—I think it's awesome! However, I'm having trouble using an icon as a prefix for a TextField. It would be great if there were an example of this in the documentation.

This is the dependency that I've in my package.json file:

`"@ownego/polaris-vue": "^2.1.4"`

I tried with the code below:

```
<script setup>
import { h } from 'vue';
import CalendarIcon from '@shopify/polaris-icons/dist/svg/CalendarIcon.svg';
import { Icon } from '@ownego/polaris-vue'
const IconPrefix = () => h(Icon, { source: CalendarIcon });
</script>

<template>
    This is displayed correctly: <IconPrefix />
    
    <TextField
        placeholder="Start date"
        v-model="dateVal"
        autoComplete="off"
        :prefix="IconPrefix()"
    />
</template>
```

Unfortunately the icon is not displayed as prefix while the icon above the TextField is rendered correctly.
I get the error "cyclic object value" on web console.

How can I change the code to achieve this requirement?

**Comment by juzser** [comment]
@alessmar you can try to use `prefix` slot.

You can see prefix slot in the Textfield documentation.
