### ISSUE TITLE
UnstyledLink custom component missing default slot

### ISSUE THREAD

**Issue by travis-r6s** [ownego/polaris-vue#410]
Was trying to use my own custom `<router-link>` component with `<AppProvider :link-component`, but there is no slot content showing - looking into the `<UnstyledLink>` component, I think it is missing the default slot for the custom component definition? See [here](https://github.com/ownego/polaris-vue/blob/9925fdc032c0bef92b2e5aef8eb93ae6633c41d9/src/components/UnstyledLink/UnstyledLink.vue#L7).

Happy to create a PR for this change if it is indeed the issue, and would be helpful!

**Comment by juzser** [comment]
Fixed on [v2.1.14](https://github.com/ownego/polaris-vue/releases/tag/v2.1.14)

**Comment by travis-r6s** [comment]
@juzser Awesome, thank you! 🙌
